Repository DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul, pull requests merged in 2022-07, with the labels that each got.

#13 [BUG] delete workflows folder (#12)
  .github/workflows/main.yml
Labels: 🐞bug

#7 [FEAT] 공동 버튼 만들기
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/UIComponent/CommonButton.swift
Labels: component

#27 [FEAT][CHORE] 가족 question UI 구현 및 placeholder 생성
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/Color+Extension.swift
  AMaDda/Global/Literal/Size.swift
  AMaDda/Global/Resource/Fonts/FontsPlaceHolder.swift
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Model/TodayQuestionData.swift
  AMaDda/Model/TodayQuestionMockData.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/ViewController.swift
  AMaDda/Screens/Main/Views/TodayQuestionView.swift
Labels: UI, 🐞bug

#25 [INIT] added character images
  AMaDda/Global/Resource/Assets.xcassets/Character1.imageset/Character1.svg
  AMaDda/Global/Resource/Assets.xcassets/Character1.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Character2.imageset/Character2.svg
  AMaDda/Global/Resource/Assets.xcassets/Character2.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Character3.imageset/Character3.svg
  AMaDda/Global/Resource/Assets.xcassets/Character3.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Character4.imageset/Character4.svg
  AMaDda/Global/Resource/Assets.xcassets/Character4.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Character5.imageset/Character5.svg
  AMaDda/Global/Resource/Assets.xcassets/Character5.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Character6.imageset/Character6.svg
  AMaDda/Global/Resource/Assets.xcassets/Character6.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Character7.imageset/Character7.svg
  AMaDda/Global/Resource/Assets.xcassets/Character7.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Character8.imageset/Character8.svg
  AMaDda/Global/Resource/Assets.xcassets/Character8.imageset/Contents.json
Labels: 🖼Assets

#30 [ADD] add onboardingImage to Assests (#22)
  AMaDda/Global/Resource/Assets.xcassets/onboardingImage.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/onboardingImage.imageset/onboardingImage.png
  AMaDda/Global/Resource/Assets.xcassets/onboardingImage.imageset/onboardingImage@2x.png
  AMaDda/Global/Resource/Assets.xcassets/onboardingImage.imageset/onboardingImage@3x.png
  AMaDda/Global/Resource/Assets.xcassets/onboardingImage.png
  AMaDda/Global/Resource/Assets.xcassets/onboardingImage@2x.png
  AMaDda/Global/Resource/Assets.xcassets/onboardingImage@3x.png
Labels: 🖼Assets

#31 [FEAT] familyTableView UI completed
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/Color+Extension.swift
  AMaDda/Model/FamilyMemberData.swift
  AMaDda/Model/FamilyMemberMockData.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/FamilyTableCell.swift
Labels: UI

#34 [FEAT] 추가하기뷰 UI 구현
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/UIImage+Extension.swift
  AMaDda/Global/Literal/ImageLiteral.swift
  AMaDda/Screens/Adding/AddingViewController.swift
Labels: UI, Adding

#39 [FEAT] reuseableIdentifier 대신하기 위해 NSObject extension 생성
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/NSObject+Extension.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/FamilyTableCell.swift
Labels: Editting, Setting

#35 [FEAT] 온보딩1 UI 구현
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Screens/Onboarding/OnboardingOneViewController.swift
Labels: 🖼Assets

#42 [FEAT] AddingView 기능 구현
  AMaDda/Global/Extension/UIViewController+Extension.swift
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Screens/Adding/AddingViewController.swift
Labels: Adding

#48 [FEAT] 푸쉬 알림 구현
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/UserDefaults+Extension.swift
  AMaDda/Model/UserNotificationManager.swift
Labels: 기능구현

#52 [Feature] UserDefaultsStateManager
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/Date+Extension.swift
  AMaDda/Global/Extension/UserDefaults+Extension.swift
  AMaDda/Model/UserDefaultsStateManager.swift
  AMaDda/Model/UserNotificationManager.swift
Labels: 기능구현

#59 [CHORE] mainView 오늘의 질문 UI 디자인 변경
  AMaDda/Global/Literal/ImageLiteral.swift
  AMaDda/Model/TodayQuestionMockData.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/TodayQuestionView.swift
Labels: Main, UI

#65 Feature/64 onboarding title
  AMaDda/Screens/Onboarding/OnboardingOneViewController.swift
  AMaDda/Screens/Onboarding/OnboardingTwoViewController.swift
Labels: UI, onboarding

#63 [FEAT] 온보딩 UI, 기능, 뷰 연결 구현
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/UserDefaults+Extension.swift
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Screens/Onboarding/OnboardingOneViewController.swift
  AMaDda/Screens/Onboarding/OnboardingTwoViewController.swift
Labels: Main, onboarding

#68 [FEAT] familyTableView UI 변경 및 userDefaults로부터 데이터 받아와 표기
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/Date+Extension.swift
  AMaDda/Global/Extension/UIImage+Extension.swift
  AMaDda/Global/Extension/UserDefaults+Extension.swift
  AMaDda/Model/FamilyMemberData.swift
  AMaDda/Model/FamilyMemberMockData.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/FamilyTableCell.swift
Labels: UI, 기능구현

#66 [FEAT] main view setting, add button
  AMaDda/Global/Literal/ImageLiteral.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/TodayQuestionView.swift
  AMaDda/Screens/Onboarding/OnboardingTwoViewController.swift
Labels: Main, UI, 기능구현

#61 [FEAT] 추가하기뷰 기능 수정
  AMaDda/Global/Extension/Color+Extension.swift
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Global/UIComponent/CommonButton.swift
  AMaDda/Screens/Adding/AddingViewController.swift
  AMaDda/Screens/ProfileModal/Controllers/ProfileModalViewController.swift
Labels: Adding, 기능구현

#69 [FEAT] empty table view
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Model/FamilyMemberMockData.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/EmptyTableViewCell.swift
Labels: Main, UI

#72 [FEAT] reload contact term string on mainVC viewWillAppear
  AMaDda/Model/FamilyMemberData.swift
  AMaDda/Model/FamilyMemberMockData.swift
  AMaDda/Screens/Main/MainViewController.swift
Labels: Editting

#77 [HOTFIX] resolved errors from merging branches
  AMaDda/Screens/Adding/AddingViewController.swift
  AMaDda/Screens/Main/MainViewController.swift
Labels: 🐞bug

#67 [FEAT] 오늘의 질문 매일마다 갱신
  AMaDda.xcodeproj/project.pbxproj
  AMaDda/Global/Extension/Collection+Extension.swift
  AMaDda/Global/Extension/UserDefaults+Extension.swift
  AMaDda/Global/Literal/TextLiteral.swift
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Model/UserDefaultsStateManager.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/TodayQuestionView.swift
Labels: Main, 기능구현

#81 [FEAT] 추가하기 누르면 데이터 반영
  AMaDda/Screens/Adding/AddingViewController.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Onboarding/OnboardingTwoViewController.swift
Labels: Main, Adding, 기능구현

#79 [HOTFIX] notificationCount setting view logic change
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Onboarding/OnboardingTwoViewController.swift
Labels: UI, 기능구현, Refactor

#80 [CHORE] divide function with id
  AMaDda/Model/FamilyMemberData.swift
  AMaDda/Screens/Main/Views/FamilyTableCell.swift
Labels: Refactor

#84 [add] 앱 아이콘 추가
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/1024.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/114.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/120.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/180.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/29.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/40.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/57.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/58.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/60.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/80.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/87.png
  AMaDda/Global/Resource/Assets.xcassets/Assets/AppIcon.appiconset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/Assets/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/appstore.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/appstore.imageset/appstore.png
  AMaDda/Global/Resource/Assets.xcassets/playstore.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/playstore.imageset/playstore.png
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Model/UserNotificationManager.swift
Labels: 🖼Assets

#89 [CHORE] bundle display name 변경
  AMaDda.xcodeproj/project.pbxproj
Labels: Editting, Setting

#94 [ADD] feedback 이미지 제작
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh1.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh1.imageset/FeedBackHigh1.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh1.imageset/FeedBackHigh1@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh1.imageset/FeedBackHigh1@3x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh2.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh2.imageset/FeedBackHigh2.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh2.imageset/FeedBackHigh2@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh2.imageset/FeedBackHigh2@3x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh3.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh3.imageset/FeedBackHigh3.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh3.imageset/FeedBackHigh3@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackHigh3.imageset/FeedBackHigh3@3x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackLow1.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedBackLow1.imageset/FeedBackLow1.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackLow1.imageset/FeedBackLow1@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedBackLow1.imageset/FeedBackLow1@3x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow2.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow2.imageset/FeedbackLow2.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow2.imageset/FeedbackLow2@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow2.imageset/FeedbackLow2@3x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow3.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow3.imageset/FeedbackLow4.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow3.imageset/FeedbackLow4@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow3.imageset/FeedbackLow4@3x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow4.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow4.imageset/FeedbackLow5.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow4.imageset/FeedbackLow5@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow4.imageset/FeedbackLow5@3x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow5.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow5.imageset/FeedbackLow6.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow5.imageset/FeedbackLow6@2x.png
  AMaDda/Global/Resource/Assets.xcassets/FeedbackLow5.imageset/FeedbackLow6@3x.png
Labels: 🖼Assets, Adding

#97 [FEAT] 연락 목표 기능 구현과 알림기능 추가
  AMaDda/Global/Extension/UserDefaults+Extension.swift
  AMaDda/Global/Literal/TextLiteral.swift
  AMaDda/Global/Supports/SceneDelegate.swift
  AMaDda/Model/UserDefaultsStateManager.swift
  AMaDda/Model/UserNotificationManager.swift
  AMaDda/Screens/Onboarding/OnboardingTwoViewController.swift
Labels: 기능구현

#107 [CHORE] fixed profile image size
  AMaDda/Screens/Main/Views/FamilyTableCell.swift
Labels: UI

#110 [CHORE] 온보딩1 이미지 autolayout 구현
  AMaDda/Screens/Onboarding/OnboardingOneViewController.swift
Labels: UI, onboarding

#101 [BUG] 버튼 무시되는 문제 해결
  AMaDda/Global/Extension/UIViewController+Extension.swift
Labels: 🐞bug

#104 [BUG] empty cell out of range error
  AMaDda/Screens/Main/MainViewController.swift
Labels: 🐞bug

#112 [FEAT] 가족 구성원 삭제 기능 구현
  AMaDda/Global/Extension/UIViewController+Extension.swift
  AMaDda/Model/FamilyMemberData.swift
  AMaDda/Screens/Editting/EdittingViewController.swift
Labels: Editting, 기능구현

#103 [FEAT] updating lastContactDate action sheet applied
  AMaDda.xcodeproj/xcshareddata/xcschemes/AMaDda.xcscheme
  AMaDda/Model/FamilyMemberData.swift
  AMaDda/Screens/Adding/AddingViewController.swift
  AMaDda/Screens/Main/MainViewController.swift
  AMaDda/Screens/Main/Views/FamilyTableCell.swift
Labels: Adding, 기능구현

#113 [FEAT] pull down button 생성
  AMaDda/Global/Literal/ImageLiteral.swift
  AMaDda/Screens/Main/MainViewController.swift
Labels: UI, 기능구현

#118 [ADD] 고양이 발바닥 버튼 추가
  AMaDda/Global/Literal/ImageLiteral.swift
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/Contents.json
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/catSole3.png
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/catSole@2x.png
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/catSole@3x.png
  AMaDda/Screens/Main/Views/FamilyTableCell.swift
Labels: Main, 🖼Assets

#123 [Bug] cat sole name
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/CatSole.png
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/CatSole@3x.png
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/Contents.json
Labels: 🐞bug, 🖼Assets

#125 [FEAT] AddingView & EditingView UI edited
  AMaDda/Screens/Adding/AddingViewController.swift
  AMaDda/Screens/Editting/EdittingViewController.swift
  AMaDda/Screens/Main/MainViewController.swift
Labels: UI, 🐞bug

#126 [HOTFIX] CatSole image
  AMaDda/Global/Resource/Assets.xcassets/catSole.imageset/CatSole.png
Labels: 🖼Assets

#127 [BUGFIX] 텍스트-> 이미지 버튼 활성화 안되던거 수정
  AMaDda/Screens/Adding/AddingViewController.swift
  AMaDda/Screens/Editting/EdittingViewController.swift
Labels: 🐞bug
